ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG RECIPE_SHA
LABEL org.senemos.recipe-sha256=${RECIPE_SHA}
RUN dnf -y --setopt=install_weak_deps=False install kmod && dnf clean all
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TZ=UTC
WORKDIR /work
